services:
  app:
    image: ${DOCKER_USER}/sample-python-app:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 1s
      timeout: 2s
      retries: 5
