name: Deploy

on:
  workflow_dispatch:

  workflow_run:  
    workflows: [Build]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            mkdir sample-python-app && cd sample-python-app
            git pull origin main
            docker compose pull
            docker compose up -d
            docker rmi -f neosupers/sample-python-app:latest