name: wokflow

on:
  push: [main]

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Uptime 
        run: uptime
      - name: Checking User Details
        run: w

  update:
    needs: uptime
    runs-on: ubuntu-latest
    steps:
      - name: Update Cache
        run: sudo apt-get update

      - name: Install Patches 
        run: sudo apt-get upgrade -y

  validate:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Update Cache
        run: sudo apt-get dist-upgrade -y