name: Build

on:
  push:
    branches: [main]
  
  workflow_run: 
    workflows: [Scan Code]
    types: [completed]

jobs:
  checkout-code:
    runs-on: self-hosted  
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v4
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
    
  build-images:
    needs: checkout-code
    runs-on: self-hosted
    steps:
      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USER != '' && format('{0}/sample-python-app:latest', vars.DOCKER_USER) || 'sample-python-app:latest' }}