#Workflow - must have a name
name: MyWorkfow

#Tells when workflow should run
on: 
  workflow_dispatch:

#Jobs - should be inside a workflow
jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name:  Say Hello
        run: echo "Hello Everyone"

      - name: update packages
        run: sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove --purge

      - name: check patch status
        run: apt upgradable --list
