#Workflow - must have a name
name: RSWorkfow

#Tells when workflow should run
on: 
  workflow_dispatch:

#Jobs - should be inside a workflow
jobs:
  say-hello:
    runs-on: ubuntu-slim
    steps:
      - name:  Say Hello
        run: echo "Hello Everyone"
